### PR TITLE
Combine "case study" components & clarify naming

### PR DESCRIPTION
**Pull request by jsms90**
#### Background
[This slide deck](https://docs.google.com/presentation/d/1UuwMTb2DBvzCoZDzWuZJmG8kkKU9yowm6bME71P7_1M/edit#slide=id.g4d4086fbac_0_17) shows the differences between design & engineering component names. It's useful to have a common language, especially for new people joining the team & looking from Zeplin to the codebase.

Met with Antonas & Tom, to agree common names, to be used across Design & Engineering (@SaraVieira please weigh in with your thoughts! :pray: ):
  - CaseStudyHero = at the top of each case study page
  - CaseStudyPreview = "featured" case study on any/all pages of website, because this is the "preview" card which leads to a full case study page

I've altered the naming in Zeplin to match - i.e. CaseStudyBanner -> CaseStudyHero
 
#### This PR
Done:
- [x] Move `CaseStudy` from `/Homepge` folder to `/Common` folder
- [x] Rename `CaseStudy` (aka CaseStudyBottom) -> `CaseStudyPreview`
- [x] Rename `topCaseStudy` (aka CaseStudyTop) -> `CaseStudyHero`
- [x] Create common layout/sizing for `CaseStudyHero` & `CaseStudyPreview` (to avoid the current situation, where clicking from [Design page](https://www.yld.io/design/) to [Canon case study](https://www.yld.io/case-study/canon-giving-stories-a-new-form), jumps visually)
- [x] Adjust `CaseStudyHero` to match designs (see [page 4 of slide deck](https://docs.google.com/presentation/d/1UuwMTb2DBvzCoZDzWuZJmG8kkKU9yowm6bME71P7_1M/edit#slide=id.g4d4086fbac_0_70))

To do:
- ~document in storybook~ - Sara handling this

### CODE REVIEW

**Comment by jsms90** [comment]
## Review template
I have opened the preview link and:

- [ ] checked that this PR resolves the spec provided from trello / this description
- [ ] checked the effected pages at all breakpoints
- [ ] ensured that this PR does not introduce any obvious bugs

**Comment by antoniocapelo** [comment]
looks good to me

**Comment by jsms90** [comment]
Brought up a couple of design discrepancies with Tom (see [slide 7 & 8 of the deck](https://docs.google.com/presentation/d/1UuwMTb2DBvzCoZDzWuZJmG8kkKU9yowm6bME71P7_1M/edit#slide=id.g4c52eecfa0_0_0)):
- [x] Top & bottom padding on component  
Solution: remove from component & handle this on a page by page basis (for now)
- [x] Title size - component docs are incorrect. Should follow page docs - i.e. changes size based on breakpoint

**Comment by hollowtf** [comment]
On Large Tablet breakpoint, remove the column between the image and the case study information

**Comment by jsms90** [comment]
@hollowtf I see that you've updated the 'Preview' component in Zeplin
image

I'm assuming you want this 1-column instead of 2-columns update on the 'Hero' component as well. Right, @hollowtf?
image

**Comment by jsms90** [comment]
Was sitting with @hollowtf as I made the changes mentioned, to ensure that I got it bang on this time :grin: 

In the process, we found another difference between the 'Hero' and 'Preview' components :sweat: Namely, the number of columns that the `Paragraph` takes up (at the desktop breakpoint):

## CaseStudyHero - Desktop (Paragraph = 4 columns)
image

## CaseStudyPreview - Desktop (Paragraph = 5 columns)
image

I didn't spot this difference between the two components when I was creating the common `CaseStudyLayout` component.

Right now, the `Layout` component defines how many columns the sub-components span. So I need to change this.

Then, hopefully merge :crossed_fingers:

**Comment by jsms90** [comment]
Currently battling with issues when running `yarn develop` locally. Weirdly don't seem to experience the same issues on netfify :confused: 

image
image

**Comment by SaraVieira** [comment]
@jsms90 run
```
rm -rf .cache && node_modules
yarn
```

gatsby ...

**Comment by jsms90** [comment]
Yeah, derp. I ran `yarn dev:clean` locally this morning and the problem was gone :+1: 

I think it was just late in the day and I'd been battling failed deployments all day because of [the related case study issue](https://trello.com/c/pYQhjXba/226-define-related-case-study-for-current-case-study-pages)

Thanks :smile:

**Comment by jsms90** [comment]
Ok from @hollowtf :tada: 

But I have run into very slight issues with implementing the grid correctly. I'm not really sure how to explain the problem online... @SaraVieira would be good to get your help when you're back? :pray:

**Pull request merged**
