### PR TITLE
request all (if more than 1000) blog posts from Contentful

### PR DESCRIPTION
**Pull request by jeysal**

### CODE REVIEW

**Comment by jeysal** [comment]
`result: []`

**Comment by jeysal** [comment]
Cause for the difference in transpilation causing errors during module loading: https://github.com/netlify/netlify-lambda/issues/200
Changed it back to `.babelrc` for now

**Comment by omonk** [comment]
I think this is default webpack behaviour no? https://github.com/netlify/netlify-lambda#webpack-configuration
I actually contributed to the netlify-lambda package to update the cli options to enable not using the babelrc flag. Previously it was breaking because the babelrc in the project uses `babel-preset-gatsby` which throws errors when used when compiling the lamdbas

**Comment by jeysal** [comment]
Yeah I noticed the `--babelrc false` as well but I don't think it is working? At least the behavior changed when I renamed from `.babelrc.js` to `.babelrc` so ...

**Comment by omonk** [comment]
Ah right yeah, it not picking up the .babelrc.js as you mentioned... we could probably make a PR to the package to update include .babelrc.js as well

**Pull request merged**
