### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by SaraVieira**
## Description - [Trello ticket](put a link to the trello ticket here)

put a short summary of what you did here

## Review template

The below is for reviewers of this PR to copy/paste into the review body and fulfill.

- Old grid break points: 0-599, 600-1095, 1095+
- New grid break points: 0-470, 471-552, 553-700, 701-899, 900-1196, 1197+

I have opened the preview link and:

- [ ] checked that this PR resolves the spec provided from trello / this description
- [ ] checked the effected pages at all breakpoints
- [ ] ensured that this PR does not introduce any obvious bugs

### CODE REVIEW

**Comment by antonasdeduchovas** [comment]
- [ ] Nav bar should not have left/right padding - logo’s left edge should align with the left edge of the content area and the right edge of the menu should align with the right edge of the content area

- [] The width of the hero image should span 6 columns and be 526px - right now it's 549

- [] Hero case study: Title of the case study is ok, but the paragraph below it is not - it should span same width as the title, 5 columns

**Comment by hollowtf** [comment]
MAIN TAKE AWAY FROM THIS QA;
When the viewport width is lower than 700px, please use the mobile designs provided and just stack content on top of each other. Key areas to focus on are the upcoming events and blog.

- [ ] Breakpoints below 1197px make the Engineeering, Design, Training section go full width instead of running over 2 columns
- [ ] Between 553px - 471px, side margins disappear on all content
- [ ] On smallest breakpoint, top case study image has side margins of 36px and a random amount, should only be 24px
- [ ] On smallest breakpoint, 'We help our clients move from...' section should have 24px side margin, currently has 36px
- [ ] Company logos seems to float below 554px breakpoint, should always have either 24/36px side margin from left hand edge
- [ ] On all mobile breakpoints (700px below) company logos sould be in 2 columns, not 3
- [ ] On breakpoints lower than 700px, please align the Upcoming events and blog section with the mobile designs, specifically making them a single column stack

**Comment by hollowtf** [comment]
Please note that logo appear to only be fixed on certain breakpoints (550px - 700px) however still seems to float unaligned on pretty much all other breakpoints.

**Comment by hollowtf** [comment]
At Small Tablet breakpoint (approx 768px) ordering of Engineering, Design, Training is incorrect.

**Comment by SaraVieira** [comment]
- [ ] Start of Engineering / Design section has 144px padding, should have 108px
- [ ] On Large tablet breakpoint, the staggered Engineering / Design section is lost
- [ ] On small tablet breakpoint, training and design seem to swap places
  - [ ] On small breakpoint, SEO page links should run the full width of their content are(half the page)
- [ ] On medium mobile breakpoint, the hamburger has not enough right hand margin, currently touvhing the edge of the container
  - [ ] On mobile, padding between Engineering, design, train sections should be 72px, not 108px
- [ ] At the end of the Engineering, Desig, Training section there appears to be unnessary padding attached to the entire section
  - [ ] On mobile, padding between DSL event block and event below is currently 42px, should be 36px
- [ ] On mobile, events are missing a the ‘Read more’ button is missing
  - [ ] On mobile, bottom of events section has 72px padding, should be 54px
- [ ] On mobile, top of blog section has an unnessary 24px padding block, please remove
  - [ ] On mobile, bottom of blog section should have padding of 54px, not 36px
- [ ] On mobile, top of Join Us section should have 36px, not 72px
  - [ ] On mobile, Join us section, there should be 36px between last job posting for london and the section title for Lisbon
- [ ] On mobile, Join us section, space between last job posting and ‘View all openings’ should be 36px, not 72px
  - [ ] On mobile, Join us section, space between View All and bottom of section should be 54px, not 36px



Mainly focussing on mobile
But can you please take note that different breakpoints have different vertical spaces, so the small tablet and mobile designs have a different vertical spacing set to the large tablet and desktop
The Case study banner component still needs work on the small tablet views, please reference the rules we have provided for it(https://zpl.io/2GojMdd)
Main thing on that is that the image should stick to the top of the section, not scale from the centre

**Comment by SaraVieira** [comment]
- [x] case study bottom component image wrong size on breakpoints below desktop

- [x] engineering case study video not horizontally centered

- [ ] top offset on engineering case study gray background too big - top of gray background should go through the middle of the video, cuts into the bottom at the moment

- [ ] `we work with` section on engineering & design page overflows on breakpoints below desktop

- [x] node js link in speciality section has underline on the trailing space.

- [ ] case study images overflow container on tablet view of Node.js page 901px - 1120px

- [ ] node.js books section alignment overlapping on 900px and below

**Pull request merged**
