### PR TITLE
Oss training section homepage

### PR DESCRIPTION
**Pull request by ZooeyMiller**
## Description - [Trello ticket](https://trello.com/c/vd7zRv5X/144-home-page-open-source-section)

this sets up the app to be able to account for the open source and training sections once they are in contentful. It is backwards compatible with the data in master on contentful, we just need to move over the data in Development on contentful to master in order for it to update on live.

To view locally run `ENV=dev yarn develop`.

This does not make it possible to show a service on the home page without a related case study.

~The [WIP] is to ensure this works with only displaying 3 services~ has been checked and this works with only 3 services.

In order to accomodate to fixes for the canon image, which was behaving weirdly before (probably due to it being a .png), I have changed the lighthouse rules to be more lenient. We should re-examine these once the new grid is in place. 

## Review template

The below is for reviewers of this PR to copy/paste into the review body and fulfill.

- Old grid break points: 0-599, 600-1095, 1095+
- New grid break points: 0-470, 471-552, 553-700, 701-899, 900-1196, 1197+

I have opened the preview link and:

- [ ] checked that this PR resolves the spec provided from trello / this description
- [ ] checked the effected pages at all breakpoints
- [ ] ensured that this PR does not introduce any obvious bugs

### CODE REVIEW

**Comment by SaraVieira** [comment]
pageReady ?

**Comment by ZooeyMiller** [comment]
@SaraVieira maybe bad naming - the idea is to go ahead with the Training and OSS sections on the homepage even when they don't link to the relevant services pages, so "pageReady" defines whether the page for the service is ready to be linked to. It currently only exists in the development environment in contentful.

**Comment by SaraVieira** [comment]
I can't see the new thingies on my phone :/

**Comment by ZooeyMiller** [comment]
@SaraVieira in order to view the new thingies you'll have to pull this branch and run it locally in dev mode - "ENV=dev yarn develop" as I can't change the stuff in contentful on master until this is merged cause it looks weird.

**Pull request merged**
